---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-6.7

suites:
  - name: default
    run_list:
      - recipe[workstation::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
